
server:
  port: 8084
spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:mysql://localhost:3306/leave_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Coder@9505
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

