
server:
  port: 8085
spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Coder@9505
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true